name: Run Playwright Tests (Python)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt
          pip install playwright  # Устанавливаем Playwright для Python
          playwright install  # Устанавливаем браузеры для Playwright

      - name: Run Playwright tests
        run: playwright test tests/  # Запускаем тесты Playwright в папке tests/

      # Optional: Upload test results as artifacts
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-screenshots-traces
          path: test-results
          retention-days: 30